const ShopActionTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
  SEND_ORDER_START: "SEND_ORDER_START",
  SEND_ORDER_SUCCESS: "SEND_ORDER_SUCCESS",
  SEND_ORDER_FAILURE: "SEND_ORDER_FAILURE",
};

export default ShopActionTypes;
